### ISSUE TITLE
TypeError when running broccoli-taco serve

### ISSUE THREAD

**Issue by silkentrance** [moudy/broccoli-fingerprint#3]
I get a TypeError when running broccoli-taco serve

```
Built with error:
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Fingerprint.getDestFilePath (/home/cklein/workspace/broccoli-taco-tests/test/node_modules/broccoli-fingerprint/index.js:43:23)
    at Fingerprint.Filter.canProcessFile (/home/cklein/workspace/broccoli-taco-tests/test/node_modules/broccoli-fingerprint/node_modules/broccoli-filter/index.js:58:15)
    at /home/cklein/workspace/broccoli-taco-tests/test/node_modules/broccoli-fingerprint/node_modules/broccoli-filter/index.js:42:18
    at /home/cklein/workspace/broccoli-taco-tests/test/node_modules/broccoli-fingerprint/node_modules/broccoli-filter/node_modules/promise-map-series/index.js:11:14
    at lib$rsvp$$internal$$tryCatch (/home/cklein/workspace/broccoli-taco-tests/test/node_modules/broccoli-fingerprint/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/cklein/workspace/broccoli-taco-tests/test/node_modules/broccoli-fingerprint/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:505:17)
    at /home/cklein/workspace/broccoli-taco-tests/test/node_modules/broccoli-fingerprint/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:1001:13
```

Having looked through the existing code, I cannot find any place where the tmpDestDir property is defined.

I am using broccoli-taco@0.0.8 and have just set up a new site using broccoli-taco new test, following the instructions presented when creating the new site.

Since the manifest, from where broccoli-taco tries to get its tmpDestDir from, is created by this, I filed the issue here instead of with broccoli-taco.

**Comment by silkentrance** [comment]
I tracked this down to broccoli-static-compiler in conjunction with fingerprint(assets-merge-tree), still debugging...

**Comment by silkentrance** [comment]
It seems that the merged tree from BroccoliMergeTrees does not have a tmpDestDir property, which ultimately boils down to broccoli-plugin and its read_compat.js module. There is an inputPath and outputPath property, though.

**Comment by silkentrance** [comment]
Using this.inputTree.outputPath instead of this.inputTree.tmpDestDir solved the issue. Will prepare a PR for this.

**Comment by michaellopez** [comment]
A note: [broccoli-static-compiler](https://github.com/joliss/broccoli-static-compiler) is deprecated in favor of [broccoli-funnel](https://github.com/broccolijs/broccoli-funnel). So the proper fix here might actually be to proceed with moudy/broccoli-taco#19

@moudy

**Comment by silkentrance** [comment]
@michaellopez ~~Does this also affect broccoli-fingerprint?  I am using broccoli-fingerprint on its own to provide for fingerprints of the available static resources...~~

Sadly, it is automatically included when creating a new site.

**Comment by cakoose** [comment]
I'm getting the same error [1] on Node 5.7.0.  @silkentrance's fix gets me past the error.  What should I do?  Should I modify my "package.json" to point at the repo with @silkentrance's fix?

[1] Full error

```
Built with error:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1227:7)
    at Fingerprint.getDestFilePath (/Users/kannan/Develop/gift-website/node_modules/broccoli-fingerprint/index.js:43:23)
    at Fingerprint.Filter.canProcessFile (/Users/kannan/Develop/gift-website/node_modules/broccoli-filter/index.js:58:15)
    at /Users/kannan/Develop/gift-website/node_modules/broccoli-filter/index.js:42:18
    at /Users/kannan/Develop/gift-website/node_modules/promise-map-series/index.js:11:14
    at lib$rsvp$$internal$$tryCatch (/Users/kannan/Develop/gift-website/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/kannan/Develop/gift-website/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/kannan/Develop/gift-website/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/kannan/Develop/gift-website/node_modules/rsvp/dist/rsvp.js:1198:9)
```

**Comment by silkentrance** [comment]
@moudy *ping*

**Comment by silkentrance** [comment]
Closing since I no longer have need for this.
